name: Create K8s ConfigMaps

on:
  push:
    paths:
      - 'test/*.json'
  pull_request:
    paths:
      - 'test/*.json'

jobs:
  create-configmap:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Process JSON files
        run: |
          for file in test/*.json; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              kubectl create configmap ${filename} --from-file=${file} -n namespace-test --dry-run=client -o yaml | kubectl apply -f -
            fi
          done