name: Create K8s ConfigMaps

on:
  push:
    paths:
      - 'characters/*.json'

jobs:
  create-configmap:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          
      - name: Process JSON files
        run: |
          for file in test/*.json; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              kubectl -n test create configmap "${filename}" \
                --from-file=config.json="./${file}" \
                -o yaml --dry-run=client | kubectl apply -f -
              echo "Created/updated ConfigMap for ${filename}"
            fi
          done